# Setup
site_url: https://liferay.design
logo_url: https://liferay.design/images/icons/liferayDesicon.svg
backend:
    name: github
    repo: liferay-design/liferay.design
    branch: master # Branch to update (optional; defaults to master)
    open_authoring: true

local_backend:
    url: http://localhost:7777/
media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow

# Collections
collections:
    - name: System
      label: People / Places
      files:
          - label: Authors
            name: Authors
            create: true
            extension: yaml
            file: src/markdown/Authors.yaml
            fields:
                - label: Authors
                  name: authors
                  widget: list
                  fields:
                      - { label: Name, name: id, widget: string }
                      - { label: Title, name: title, widget: string }
                      - { label: Active, name: active, widget: boolean }
                      - { label: Icon, name: icon, widget: string }
                      - { label: Start Date, name: date, widget: datetime }
                      - {
                            label: Office,
                            name: office,
                            widget: relation,
                            collection: Offices,
                            search_fields: [id],
                            value_field: id,
                        }
          - label: Offices
            name: Offices
            file: src/markdown/Offices.yaml
            create: true
            extension: yaml
            fields:
                - label: Offices
                  name: id
                  widget: list
                  fields:
                      - { label: Name, name: id, widget: string }
                      - { label: Flag Icon, name: regionIcon, widget: string }
                      - { label: City, name: city, widget: string }
                      - { label: Region, name: region, widget: string }
                      - { label: Country, name: country, widget: string }
                      - { label: Google Map URL, name: mapURL, widget: string }
    - name: articles
      label: Articles
      folder: src/markdown/articles/
      path: '{{year}}/{{slug}}'
      create: true
      fields:
          - { label: Author, name: author, widget: string }
          - { label: Publish Date, name: date, widget: datetime }
          - { label: Title, name: title, widget: string }
          - { label: Featured Image, name: featuredImage, widget: image }
          - { label: Publish, name: publish, widget: boolean }
          - { label: Body, name: body, widget: markdown }
    - name: handbook
      label: Handbook
      folder: src/markdown/handbook/
      format: frontmatter
      extension: 'mdx'
      path: '{{dirname}}/{{slug}}'
      create: true
      fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: Order, name: order, widget: number }
          - { label: Publish, name: publish, widget: boolean }
          - { label: Body, name: body, widget: mdx }
    - name: careers
      label: Careers
      folder: src/markdown/careers/
      path: '{{dirname}}/{{slug}}'
      view_filters:
          - label: Active
            field: published
            pattern: true
          - label: APAC
            field: office
            pattern: 'Tokyo'
          - label: EMEA
            field: office
            pattern: 'Madrid'
          - label: NA
            field: office
            pattern: 'Diamond Bar'
          - label: LATAM
            field: office
            pattern: 'Recife'
      create: true
      fields:
          - { label: Jobvite ID, name: jobId, widget: string }
          - { label: Publish Date, name: date, widget: datetime }
          - { label: Title, name: title, widget: string }
          - { label: Location, name: office, widget: string }
          - { label: Featured Image, name: featuredImage, widget: image }
          - { label: Publish, name: published, widget: boolean }
          - { label: Body, name: body, widget: markdown }
